export interface HistoricalFigure {
    id: string;
    wikiTitleEn: string;
    wikiTitleKo: string;
    era: string;
    category: 'leader' | 'artist' | 'scientist' | 'thinker' | 'warrior';
}

export const pastLifeFigures: HistoricalFigure[] = [
    { id: 'napoleon', wikiTitleEn: 'Napoleon', wikiTitleKo: '나폴레옹_보나파르트', era: '18th Century', category: 'leader' },
    { id: 'cleopatra', wikiTitleEn: 'Cleopatra', wikiTitleKo: '클레오파트라_7세', era: 'Ancient Egypt', category: 'leader' },
    { id: 'davinci', wikiTitleEn: 'Leonardo_da_Vinci', wikiTitleKo: '레오나르도_다_빈치', era: 'Renaissance', category: 'artist' },
    { id: 'elizabeth1', wikiTitleEn: 'Elizabeth_I', wikiTitleKo: '엘리자베스_1세', era: '16th Century', category: 'leader' },
    { id: 'khan', wikiTitleEn: 'Genghis_Khan', wikiTitleKo: '칭기즈_칸', era: '13th Century', category: 'leader' },
    { id: 'joan', wikiTitleEn: 'Joan_of_Arc', wikiTitleKo: '잔_다르크', era: '15th Century', category: 'warrior' },
    { id: 'alexander', wikiTitleEn: 'Alexander_the_Great', wikiTitleKo: '알렉산드로스_3세', era: 'Ancient Greece', category: 'leader' },
    { id: 'antoinette', wikiTitleEn: 'Marie_Antoinette', wikiTitleKo: '마리_앙투아네트', era: '18th Century', category: 'leader' },
    { id: 'mozart', wikiTitleEn: 'Wolfgang_Amadeus_Mozart', wikiTitleKo: '볼프강_아마데우스_모차르트', era: '18th Century', category: 'artist' },
    { id: 'caesar', wikiTitleEn: 'Julius_Caesar', wikiTitleKo: '율리우스_카이사르', era: 'Ancient Rome', category: 'leader' },
    { id: 'curie', wikiTitleEn: 'Marie_Curie', wikiTitleKo: '마리_퀴리', era: '19th Century', category: 'scientist' },
    { id: 'lincoln', wikiTitleEn: 'Abraham_Lincoln', wikiTitleKo: '에이브러햄_링컨', era: '19th Century', category: 'leader' },
    { id: 'sejong', wikiTitleEn: 'Sejong_the_Great', wikiTitleKo: '세종', era: '15th Century', category: 'leader' },
    { id: 'sunshin', wikiTitleEn: 'Yi_Sun-sin', wikiTitleKo: '이순신', era: '16th Century', category: 'warrior' },
    { id: 'nobunaga', wikiTitleEn: 'Oda_Nobunaga', wikiTitleKo: '오다_노부나가', era: '16th Century', category: 'leader' },
    { id: 'shakespeare', wikiTitleEn: 'William_Shakespeare', wikiTitleKo: '윌리엄_셰익스피어', era: 'Renaissance', category: 'artist' },
    { id: 'einstein', wikiTitleEn: 'Albert_Einstein', wikiTitleKo: '알베르트_아인슈타인', era: '20th Century', category: 'scientist' },
    { id: 'kahlo', wikiTitleEn: 'Frida_Kahlo', wikiTitleKo: '프리다_칼로', era: '20th Century', category: 'artist' },
    { id: 'gandhi', wikiTitleEn: 'Mahatma_Gandhi', wikiTitleKo: '마하트마_간디', era: '20th Century', category: 'leader' },
    { id: 'mandela', wikiTitleEn: 'Nelson_Mandela', wikiTitleKo: '넬슨_만델라', era: '20th Century', category: 'leader' },
    { id: 'churchill', wikiTitleEn: 'Winston_Churchill', wikiTitleKo: '윈스턴_처칠', era: '20th Century', category: 'leader' },
    { id: 'mlk', wikiTitleEn: 'Martin_Luther_King_Jr.', wikiTitleKo: '마틴_루터_킹_주니어', era: '20th Century', category: 'leader' },
    { id: 'earhart', wikiTitleEn: 'Amelia_Earhart', wikiTitleKo: '어멜리아_이어하트', era: '20th Century', category: 'scientist' },
    { id: 'michelangelo', wikiTitleEn: 'Michelangelo', wikiTitleKo: '미켈란젤로_부오나로티', era: 'Renaissance', category: 'artist' },
    { id: 'galileo', wikiTitleEn: 'Galileo_Galilei', wikiTitleKo: '갈릴레오_갈릴레이', era: 'Renaissance', category: 'scientist' },
    { id: 'newton', wikiTitleEn: 'Isaac_Newton', wikiTitleKo: '아이작_뉴턴', era: '17th Century', category: 'scientist' },
    { id: 'darwin', wikiTitleEn: 'Charles_Darwin', wikiTitleKo: '찰스_다윈', era: '19th Century', category: 'scientist' },
    { id: 'freud', wikiTitleEn: 'Sigmund_Freud', wikiTitleKo: '지그문트_프로이트', era: '19th Century', category: 'thinker' },
    { id: 'vangogh', wikiTitleEn: 'Vincent_van_Gogh', wikiTitleKo: '빈센트_반_고흐', era: '19th Century', category: 'artist' },
    { id: 'picasso', wikiTitleEn: 'Pablo_Picasso', wikiTitleKo: '파블로_피카소', era: '20th Century', category: 'artist' },
    { id: 'beethoven', wikiTitleEn: 'Ludwig_van_Beethoven', wikiTitleKo: '루트비히_판_베토벤', era: '19th Century', category: 'artist' },
    { id: 'tchaikovsky', wikiTitleEn: 'Pyotr_Ilyich_Tchaikovsky', wikiTitleKo: '표트르_차이콥스키', era: '19th Century', category: 'artist' },
    { id: 'catherine', wikiTitleEn: 'Catherine_the_Great', wikiTitleKo: '예카테리나_2세', era: '18th Century', category: 'leader' },
    { id: 'peter', wikiTitleEn: 'Peter_the_Great', wikiTitleKo: '표트르_1세', era: '18th Century', category: 'leader' },
    { id: 'suntzu', wikiTitleEn: 'Sun_Tzu', wikiTitleKo: '손무', era: 'Ancient China', category: 'warrior' },
    { id: 'confucius', wikiTitleEn: 'Confucius', wikiTitleKo: '공자', era: 'Ancient China', category: 'thinker' },
    { id: 'buddha', wikiTitleEn: 'Gautama_Buddha', wikiTitleKo: '고타마_붓다', era: 'Ancient India', category: 'thinker' },
    { id: 'socrates', wikiTitleEn: 'Socrates', wikiTitleKo: '소크라테스', era: 'Ancient Greece', category: 'thinker' },
    { id: 'plato', wikiTitleEn: 'Plato', wikiTitleKo: '플라톤', era: 'Ancient Greece', category: 'thinker' },
    { id: 'aristotle', wikiTitleEn: 'Aristotle', wikiTitleKo: '아리스토텔레스', era: 'Ancient Greece', category: 'thinker' },
    { id: 'polo', wikiTitleEn: 'Marco_Polo', wikiTitleKo: '마르코_폴로', era: '13th Century', category: 'scientist' },
    { id: 'columbus', wikiTitleEn: 'Christopher_Columbus', wikiTitleKo: '크리스토퍼_콜럼버스', era: '15th Century', category: 'leader' },
    { id: 'gama', wikiTitleEn: 'Vasco_da_Gama', wikiTitleKo: '바스쿠_다_가마', era: '15th Century', category: 'leader' },
    { id: 'magellan', wikiTitleEn: 'Ferdinand_Magellan', wikiTitleKo: '페르디난드_마젤란', era: '16th Century', category: 'leader' },
    { id: 'cortes', wikiTitleEn: 'Hernan_Cortes', wikiTitleKo: '에르난_코르테스', era: '16th Century', category: 'warrior' },
    { id: 'nefertiti', wikiTitleEn: 'Nefertiti', wikiTitleKo: '네페르티티', era: 'Ancient Egypt', category: 'leader' },
    { id: 'tut', wikiTitleEn: 'Tutankhamun', wikiTitleKo: '투탕카멘', era: 'Ancient Egypt', category: 'leader' },
    { id: 'ramses', wikiTitleEn: 'Ramesses_II', wikiTitleKo: '람세스_2세', era: 'Ancient Egypt', category: 'leader' },
    { id: 'hatshepsut', wikiTitleEn: 'Hatshepsut', wikiTitleKo: '하트셉수트', era: 'Ancient Egypt', category: 'leader' },
    { id: 'boudica', wikiTitleEn: 'Boudica', wikiTitleKo: '보우디카', era: 'Ancient Rome', category: 'warrior' },
];
